Add files via upload
En saa ladattua kansiota kaikkine tiedostoineen, kun on liian iso. Ja taas bash:n kautta se ei suostu latamaan, koska valittaa 

OMISTAJA@DESKTOP-7DTF2PI MINGW64 ~/Documents/Opinnot Syksy 2024/Webohjelmointi/Viikko3 (main)
$ git push -u origin main
To https://github.com/c2lael03/WEBEXPO.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/c2lael03/WEBEXPO.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.